# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: prettyplease-backend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  profile: serverless
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}

# you can overwrite defaults here
#  stage: dev
  region: eu-west-2

package:
  artifact: target/prettyplease-dev.jar

functions:
  getsponsor:
    handler: com.prettyplease.SponsorHandler
    events:
      - http:
          path: sponsors/{sponsorId}
          method: get

  createsponsor:
    handler: com.prettyplease.SponsorHandler
    events:
      - http:
          path: sponsors
          method: post
          cors: true

  getcharity:
    handler: com.prettyplease.CharityHandler
    events:
      - http:
          path: charities/{charityId}
          method: get
          cors: true

  createcharity:
    handler: com.prettyplease.CharityHandler
    events:
      - http:
          path: charities
          method: post
          cors: true

# always going to get the request with the charity details
  getrequest:
    handler: com.prettyplease.RequestHandler
    events:
      - http:
          path: requests/{requestId}
          method: get
          cors: true

# requests joined with charity details
  getsponsorrequest:
    handler: com.prettyplease.CharityRequestHandler
    events:
      - http:
          path: sponsorrequests/{requestId}
          method: get
          cors: true

#  listcharityrequests:
#    handler: com.prettyplease.CharityRequestHandler
#    events:
#      - http:
#          path: requests
#          method: get
#          cors: true

#  listrequests:
#    handler: com.prettyplease.RequestHandler
#    events:
#      - http:
#          path: requests
#          method: get
#          cors: true

#  listrequestsbystatus:
#    handler: com.prettyplease.RequestHandler
#    events:
#      - http:
#          path: requests/{status}??? or query parameter?
#          method: get
#          cors: true

  createrequest:
    handler: com.prettyplease.RequestHandler
    events:
      - http:
          path: requests
          method: post
          cors: true

#  updaterequest:
#    handler: com.prettyplease.UpdateRequestHandler
#    events:
#      - http:
#          path: requests/{requestId}
#          method: put
#          cors: true
#
#  getoffer:
#    handler: com.prettyplease.GetOfferHandler
#    events:
#      - http:
#          path: offers/{offerId}
#          method: get
#          cors: true

  listcharityoffers:
    handler: com.prettyplease.CharityOfferHandler
    events:
      - http:
          path: charityoffers/{charityId}
          method: get
          cors: true

  listsponsoroffers:
    handler: com.prettyplease.SponsorOfferHandler
    events:
      - http:
          path: sponsoroffers/{sponsorId}
          method: get
          cors: true


#  listoffers:
#    handler: com.prettyplease.ListOfferHandler
#    events:
#      - http:
#          path: offers
#          method: get
#          cors: true
#
#  createoffer:
#    handler: com.prettyplease.CreateOfferHandler
#    events:
#      - http:
#          path: offers
#          method: post
#          cors: true
#
#  updateoffer:
#    handler: com.prettyplease.UpdateOfferHandler
#    events:
#      - http:
#          path: offers/{offerId}
#          method: put
#          cors: true
